# Generated by Django 3.2 on 2021-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EXP_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS_IVDATEG', models.DateTimeField()),
                ('PS_BR_CODE', models.CharField(default='null', max_length=5)),
                ('BR_NAMEA', models.CharField(max_length=100)),
                ('BR_NAMEL', models.CharField(max_length=100)),
                ('SM_CODE', models.CharField(default='null', max_length=5)),
                ('SM_NAME', models.CharField(max_length=200)),
                ('PRCU_CODE', models.CharField(default='null', max_length=5)),
                ('PRCU_NAME', models.CharField(default='null', max_length=5)),
                ('MOBILE', models.CharField(default='null', max_length=5)),
                ('PRCUCT_NAME', models.CharField(default='null', max_length=5)),
                ('CT_DISCOUNT', models.CharField(default=0, max_length=5)),
                ('count', models.CharField(blank=True, max_length=5, null=True)),
                ('TOTALPRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('NET_PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('POINTS_GAINED', models.CharField(blank=True, max_length=5, null=True)),
                ('POINTS_USED', models.CharField(blank=True, max_length=5, null=True)),
                ('POINTS_DISCOUNT', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
