# Generated by Django 3.2 on 2021-04-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_exp_report_ps_ivdateg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp_report',
            name='BR_NAMEA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='BR_NAMEL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='CT_DISCOUNT',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='MOBILE',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='NET_PRICE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PRCUCT_NAME',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PRCU_CODE',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PRCU_NAME',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PS_BR_CODE',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='SM_CODE',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='SM_NAME',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='TOTALPRICE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
