# Generated by Django 3.2 on 2021-04-24 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_exp_report_ps_ivdateg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp_report',
            name='BR_NAMEA',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='BR_NAMEL',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='CT_DISCOUNT',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='MOBILE',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='NET_PRICE',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='POINTS_DISCOUNT',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='POINTS_GAINED',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='POINTS_USED',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='PRCUCT_NAME',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='PRCU_CODE',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='PRCU_NAME',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='PS_BR_CODE',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='SM_CODE',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='SM_NAME',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='TOTALPRICE',
        ),
        migrations.RemoveField(
            model_name='exp_report',
            name='count',
        ),
    ]
