# Generated by Django 3.2 on 2021-04-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20210424_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp_report',
            name='PS_IVDATEG',
        ),
        migrations.AddField(
            model_name='exp_report',
            name='PS_BR_CODE',
            field=models.CharField(blank=True, default='null', max_length=5, null=True),
        ),
    ]
