# Generated by Django 3.2 on 2021-04-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20210424_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp_report',
            name='CT_DISCOUNT',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='MOBILE',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='POINTS_DISCOUNT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='POINTS_GAINED',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='POINTS_USED',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PRCUCT_NAME',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PRCU_CODE',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='PRCU_NAME',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='SM_CODE',
            field=models.CharField(blank=True, default='null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_report',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
